export const Head = () => {
    return (
        <head>
            <title>Fitness Fanatic</title>
            <meta name="description" content="Fitness Fanatic, a fitness app generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="https://img.icons8.com/cotton/64/dumbbell--v2.png" />
        </head>
    )
}